server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/wp-content/uploads/(.*)$ {
        return 301 https://cdn.fitdoplnky.sk/$1;
    }

    location ~ ^/(obchod|produkt)(/.*)?$ {
        return 301 /obchod/;
    }

    location ~ ^/kategoria-produktu(/.*)?$ {
        return 301 /kategoria-produktu/;
    }

    location ~ ^/(tag|znacka)(/.*)?$ {
        return 301 /tag/;
    }

    location ~ ^/author(/.*)?$ {
        return 301 /author/;
    }

    location = /kontakt {
        return 301 /stranky/kontakt/;
    }

    location = /ochrana-osobnych-udajov {
        return 301 /stranky/ochrana-osobnych-udajov/;
    }

    location ~ ^/([^./]+?)/?$ {
        return 301 /clanky/$1/;
    }

    location / {
        try_files $uri $uri/ $uri.html /404.html;
    }
}
