server {
    listen 80;
    server_name _;

    location ~ ^/wp-content/uploads/(.*)$ {
        return 301 https://cdn.fitdoplnky.sk/$1;
    }

    location ~ ^/(obchod|produkt|kategoria-produktu|tag|author|znacka)(/.*)?$ {
        return 301 https://www.fitdoplnky.sk/$1/;
    }

    location ~ ^/(wp-admin|wp-login\.php|xmlrpc\.php|feed)(/.*)?$ {
        return 301 https://www.fitdoplnky.sk/;
    }

    location / {
        return 301 https://www.fitdoplnky.sk$request_uri;
    }
}
